// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health": {
            "get": {
                "description": "检查服务是否正常运行",
                "produces": ["application/json"],
                "tags": ["系统"],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {"type": "string", "example": "ok"}
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "用户登录获取访问令牌",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["认证"],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["username", "password"],
                            "properties": {
                                "username": {"type": "string", "example": "admin"},
                                "password": {"type": "string", "example": "password123"},
                                "rememberMe": {"type": "boolean", "example": false}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "code": {"type": "integer", "example": 0},
                                "message": {"type": "string", "example": "success"},
                                "data": {
                                    "type": "object",
                                    "properties": {
                                        "accessToken": {"type": "string"},
                                        "refreshToken": {"type": "string"},
                                        "expiresIn": {"type": "integer"}
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误"
                    }
                }
            }
        },
        "/api/admin/suppliers": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "获取所有供应商列表",
                "produces": ["application/json"],
                "tags": ["管理员-供应商管理"],
                "summary": "获取供应商列表",
                "parameters": [
                    {"name": "page", "in": "query", "type": "integer", "default": 1},
                    {"name": "pageSize", "in": "query", "type": "integer", "default": 20},
                    {"name": "status", "in": "query", "type": "boolean"}
                ],
                "responses": {
                    "200": {"description": "成功"}
                }
            },
            "post": {
                "security": [{"Bearer": []}],
                "description": "创建新供应商",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["管理员-供应商管理"],
                "summary": "创建供应商",
                "responses": {
                    "200": {"description": "创建成功"}
                }
            }
        },
        "/api/admin/stores": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "获取所有门店列表",
                "produces": ["application/json"],
                "tags": ["管理员-门店管理"],
                "summary": "获取门店列表",
                "responses": {
                    "200": {"description": "成功"}
                }
            }
        },
        "/api/admin/materials": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "获取所有物料列表",
                "produces": ["application/json"],
                "tags": ["管理员-物料管理"],
                "summary": "获取物料列表",
                "responses": {
                    "200": {"description": "成功"}
                }
            }
        },
        "/api/admin/orders": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "管理员获取所有订单列表",
                "produces": ["application/json"],
                "tags": ["管理员-订单管理"],
                "summary": "获取订单列表",
                "responses": {
                    "200": {"description": "成功"}
                }
            }
        },
        "/api/supplier/orders": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "供应商获取订单列表",
                "produces": ["application/json"],
                "tags": ["供应商-订单管理"],
                "summary": "获取订单列表",
                "responses": {
                    "200": {"description": "成功"}
                }
            }
        },
        "/api/supplier/materials": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "获取供应商物料列表",
                "produces": ["application/json"],
                "tags": ["供应商-物料管理"],
                "summary": "获取物料列表",
                "responses": {
                    "200": {"description": "成功"}
                }
            }
        },
        "/api/store/materials": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "门店浏览可订购物料",
                "produces": ["application/json"],
                "tags": ["门店-物料浏览"],
                "summary": "获取物料列表",
                "responses": {
                    "200": {"description": "成功"}
                }
            }
        },
        "/api/store/cart": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "获取购物车内容",
                "produces": ["application/json"],
                "tags": ["门店-购物车"],
                "summary": "获取购物车",
                "responses": {
                    "200": {"description": "成功"}
                }
            }
        },
        "/api/store/orders": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "门店获取订单列表",
                "produces": ["application/json"],
                "tags": ["门店-订单管理"],
                "summary": "获取订单列表",
                "responses": {
                    "200": {"description": "成功"}
                }
            },
            "post": {
                "security": [{"Bearer": []}],
                "description": "门店创建新订单",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["门店-订单管理"],
                "summary": "创建订单",
                "responses": {
                    "200": {"description": "创建成功"}
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\""
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "供应链订货系统 API",
	Description:      "供应链订货系统后端API接口文档，支持管理员、供应商、门店三种角色",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
