package docs

import (
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
	_ "github.com/project/backend/docs" // docs is generated by Swag CLI
)

// @title Supply Chain Order System API
// @version 1.0
// @description API documentation for Supply Chain Order Management System
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email support@example.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1

// @securityDefinitions.apikey Bearer
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

// SetupSwagger configures Swagger documentation
func SetupSwagger(e *echo.Echo) {
	// Serve Swagger UI at /swagger/*
	e.GET("/swagger/*", echoSwagger.WrapHandler)
}

// Response models for Swagger documentation

// SuccessResponse represents a successful API response
type SuccessResponse struct {
	Code      int         `json:"code" example:"0"`
	Message   string      `json:"message" example:"Success"`
	Data      interface{} `json:"data"`
	Timestamp int64       `json:"timestamp" example:"1640995200"`
}

// ErrorResponse represents an error API response
type ErrorResponse struct {
	Code      int    `json:"code" example:"400"`
	Message   string `json:"message" example:"Bad Request"`
	Error     string `json:"error,omitempty"`
	Timestamp int64  `json:"timestamp" example:"1640995200"`
}

// PaginationQuery represents pagination parameters
type PaginationQuery struct {
	Page     int    `query:"page" json:"page" example:"1"`
	PageSize int    `query:"pageSize" json:"pageSize" example:"20"`
	Sort     string `query:"sort" json:"sort,omitempty" example:"created_at"`
	Order    string `query:"order" json:"order,omitempty" example:"desc"`
}

// PaginatedResponse represents a paginated response
type PaginatedResponse struct {
	Items      interface{} `json:"items"`
	Total      int64       `json:"total" example:"100"`
	Page       int         `json:"page" example:"1"`
	PageSize   int         `json:"pageSize" example:"20"`
	TotalPages int         `json:"totalPages" example:"5"`
}
